export {ReactComponent as Wallet } from './uil_wallet.svg';
export {ReactComponent as Moon } from './uil_moon.svg';
export {ReactComponent as User } from './uil_user.svg';
export {ReactComponent as Settings } from './uil_setting.svg';
export {ReactComponent as Angle } from './uil_angle-down.svg';
export {ReactComponent as Info } from './uil_info-circle.svg';
export {ReactComponent as CircledCheck } from './uil_check-circle.svg';
export {ReactComponent as Check } from './uil_check.svg';
export {ReactComponent as Copy } from './uil_copy.svg';
export {ReactComponent as CircledCross } from './uil_times-circle.svg';
export {ReactComponent as Trash } from './uil_trash.svg';
export {ReactComponent as Cross } from './uil_multiply.svg';
export {ReactComponent as Edit } from './uil_edit.svg';
export {ReactComponent as Search } from './uil_search.svg';
export {ReactComponent as EnvelopeSearch } from './uil_envelope-search.svg';
export {ReactComponent as Exchange } from './uil_exchange.svg';
export {ReactComponent as Brightness } from './uil_brightness.svg';
export {ReactComponent as Calendar } from './uil_calendar-alt.svg';
export {ReactComponent as PhoneSearch } from './uil_mobile-android-search.svg';
export {ReactComponent as CornerArrow } from './uil_corner-down-r.svg';
export {ReactComponent as Eye } from './uil_eye.svg';
export {ReactComponent as EyeSlash } from './uil_eye-slash.svg';
export {ReactComponent as Logo } from './logo.svg';
export {ReactComponent as Login } from './uil_signin.svg';
export {ReactComponent as Logout } from './uil_signin.svg';
export {ReactComponent as Telegram} from './uil_telegram-alt.svg';
export {ReactComponent as Mail} from './uil_envelope.svg';
export {ReactComponent as ToolTipNeedle} from './tool-tip.svg';
export {ReactComponent as Spinner} from './uil_spinner.svg';

